0 0 dataAuditErrors
482 0 4B.1A: Minimum width of ME1 region is 0.16um
486 0 4B.1B: Maximum width of ME1 region is 25um
493 0 4B.1C: Minimum space between ME1 regions is 0.16um
506 0 4B.1C.a: Minimum space between ME1 regions is 0.26 where one ME1 width > 1.76um
514 0 4B.1D.a: Minimum ME1 overlap contac is 0um, no CONT outside ME1
529 0 4B.1D.bc: Minimum metal enclosure of CONT at end-of-line or outer corner is 0.06um when metal-1 width < 0.24um
561 0 4B.1D.d Metal1 (EOL) overlap of contact for M1 width < 0.18um and spacing to three adjacent M1 <= 0.18um is 0.10um
565 0 4B.1E: Minimum area of ME1 region 0.1024 sq.um
567 0 4B.1F: Minimum ME1 enclosed area 0.3072 sq.um
573 0 4B.3A: Minimum width of ME2 region is 0.2um
577 0 4B.3B: Maximum width of ME2 region is 25um
582 0 4B.3C: Minimum space between ME2 regions is 0.2um
595 0 4B.3C.a: Minimum space between ME2 regions is 0.28 where one ME2 width > 2um
597 0 4B.3D_M: Minimum ME2 overlap contac is 0um, no VI1 outside ME2
599 0 4B.3E: Minimum area of ME2 region 0.1024 sq.um
601 0 4B.3F: Minimum ME2 enclosed area 0.3072 sq.um
607 0 4B.5A: Minimum width of ME3 region is 0.2um
611 0 4B.5B: Maximum width of ME3 region is 25um
615 0 4B.5C: Minimum space between ME3 regions is 0.2um
628 0 4B.5C.a: Minimum space between ME3 regions is 0.28 where one ME3 width > 2um
630 0 4B.5D_M: Minimum ME3 overlap contac is 0um, no VI1 outside ME3
632 0 4B.5E: Minimum area of ME3 region 0.1024 sq.um
634 0 4B.5F: Minimum ME3 enclosed area 0.3072 sq.um
640 0 4B.7A: Minimum width of ME4 region is 0.2um
644 0 4B.7B: Maximum width of ME4 region is 25um
648 0 4B.7C: Minimum space between ME4 regions is 0.2um
661 0 4B.7C.a: Minimum space between ME4 regions is 0.28 where one ME4 width > 2um
663 0 4B.7D_M: Minimum ME4 overlap contac is 0um, no VI1 outside ME4
665 0 4B.7E: Minimum area of ME4 region 0.1024 sq.um
667 0 4B.7F: Minimum ME4 enclosed area 0.3072 sq.um
673 0 4B.9A: Minimum width of ME5 region is 0.2um
677 0 4B.9B: Maximum width of ME5 region is 25um
681 0 4B.9C: Minimum space between ME5 regions is 0.2um
694 0 4B.9C.a: Minimum space between ME5 regions is 0.28 where one ME5 width > 2um
696 0 4B.9D_M: Minimum ME5 overlap contac is 0um, no VI1 outside ME5
698 0 4B.9E: Minimum area of ME5 region 0.1024 sq.um
700 0 4B.9F: Minimum ME5 enclosed area 0.3072 sq.um
706 0 4B.11A: Minimum width of ME6 region is 0.2um
710 0 4B.11B: Maximum width of ME6 region is 25um
714 0 4B.11C: Minimum space between ME6 regions is 0.2um
727 0 4B.11C.a: Minimum space between ME6 regions is 0.28 where one ME6 width > 2um
729 0 4B.11D_M: Minimum ME6 overlap contac is 0um, no VI1 outside ME6
731 0 4B.11E: Minimum area of ME6 region 0.1024 sq.um
733 0 4B.11F: Minimum ME6 enclosed area 0.3072 sq.um
741 0 4B.2A__4B.21.2.3M.VI1: Minimum and maximum width of a VI1 region is 0.20um
749 0 4B.2B.a: Minimum space between two VI1 regions  is 0.20um
767 0 4B.2B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
773 0 4B.2C.a: Minimum metal-1 enclosure of via1 is -0.02um, no via1 outside metal-1
775 0 4B.2C.b: Minimum metal-1( width >= 0.2um ) enclosure of via1 is 0, no via1 outside metal-1
786 0 4B.2C.cd: Minimum metal-1 enclosure of via1 at end-of-line or outer corner is 0.06um when metal-1 width < 0.24um
793 0 4B.2C.e: Minimum metal1 (EOL) enclosure of via for metal-1 width < 0.18um and spacing to three adjacent M1 <= 0.18um is 0.10um
818 0 4B.2D: When metal-1 or metal-2 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-1 and metal-2
821 0 4B.2E: Via1 edges should be horizontal or vertical
828 0 4B.4A__4B.21.2.3M.VI2: Minimum and maximum width of a VI2 region is 0.20um
836 0 4B.4B.a: Minimum space between two VI2 regions  is 0.20um
854 0 4B.4B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
856 0 4B.4C.a_M: Minimum metal-2 enclosure of via2 is 0um, no via2 outside metal-2
864 0 4B.4C.bc_M : Minimum metal-2 enclosure of via2 at end-of-line or outer corner is 0.06um when metal-2 width < 0.24um
889 0 4B.4D: When metal-2 or metal-3 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-2 and metal-3
892 0 4B.4E: Via2 edges should be horizontal or vertical
899 0 4B.6A__4B.21.2.3M.VI3: Minimum and maximum width of a VI3 region is 0.20um
907 0 4B.6B.a: Minimum space between two VI3 regions  is 0.20um
925 0 4B.6B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
926 0 4B.6C.a_M: Minimum metal-3 enclosure of via3 is 0um, no via3 outside metal-3
934 0 4B.6C.bc_M : Minimum metal-3 enclosure of via3 at end-of-line or outer corner is 0.06um when metal-3 width < 0.24um
959 0 4B.6D: When metal-3 or metal-4 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-3 and metal-4
962 0 4B.6E: Via3 edges should be horizontal or vertical
969 0 4B.8A__4B.21.2.3M.VI4: Minimum and maximum width of a VI4 region is 0.20um
977 0 4B.8B.a: Minimum space between two VI4 regions  is 0.20um
995 0 4B.8B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
996 0 4B.8C.a_M: Minimum metal-4 enclosure of via4 is 0um, no via4 outside metal-4
1004 0 4B.8C.bc_M : Minimum metal-4 enclosure of via4 at end-of-line or outer corner is 0.06um when metal-4 width < 0.24um
1029 0 4B.8D: When metal-4 or metal-5 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-4 and metal-5
1032 0 4B.8E: Via4 edges should be horizontal or vertical
1039 0 4B.10A__4B.21.2.3M.VI5: Minimum and maximum width of a VI5 region is 0.20um
1047 0 4B.10B.a: Minimum space between two VI5 regions  is 0.20um
1065 0 4B.10B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
1066 0 4B.10C.a_M: Minimum metal-5 enclosure of via5 is 0um, no via5 outside metal-5
1074 0 4B.10C.bc_M : Minimum metal-5 enclosure of via5 at end-of-line or outer corner is 0.06um when metal-5 width < 0.24um
1099 0 4B.10D: When metal-5 or metal-6 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-5 and metal-6
1102 0 4B.10E: Via5 edges should be horizontal or vertical
1121 0 4B.2F: Viafarm density of via1 <= 30%
1141 0 4B.4F: Viafarm density of via2 <= 30%
1161 0 4B.6F: Viafarm density of via3 <= 30%
1181 0 4B.8F: Viafarm density of via4 <= 30%
1201 0 4B.10F: Viafarm density of via5 <= 30%
1218 0 4B.10F_TV: Viafarm density of via5 <= 30%
1221 0 4B.16B_M1: Maximum width of metal-1 over M1SLMK is 10um
1224 0 4B.17B_M2: Maximum width of metal-2 over M2SLMK is 10um
1227 0 4B.17B_M3: Maximum width of metal-3 over M3SLMK is 10um
1230 0 4B.17B_M4: Maximum width of metal-4 over M4SLMK is 10um
1233 0 4B.17B_M5: Maximum width of metal-5 over M5SLMK is 10um
1236 0 4B.17B_M6: Maximum width of metal-6 over M6SLMK is 10um
1244 0 Warning_4B_21_1_PAD1: PAD mark layer only can draw in PAD area
1255 0 Warning_4B_21_1_PAD2: One chip include 2 kind of PAD structure is not allowed
1279 0 4B.21.2.3 C: Minimum ME6 enclosure of TMV_RDL is 2.0um, no TMV_RDL outside ME6
1283 0 4B.21.2.3 H.ME6 : Pad ME6 has the same size as AL_RDL pad
1287 0 4B.21.2.3 H.ME5 : Pad ME5 has the same size as AL_RDL pad
1291 0 4B.21.2.3 H.ME4 : Pad ME4 has the same size as AL_RDL pad
1295 0 4B.21.2.3 H.ME3 : Pad ME3 has the same size as AL_RDL pad
1299 0 4B.21.2.3 H.ME2 : Pad ME2 has the same size as AL_RDL pad
1303 0 4B.21.2.3 H.ME1 : Pad ME1 has the same size as AL_RDL pad
1305 0 4B.21.2.3 I.ME6 : Minimum width of a ME6 slot region is 1.2um X 1.2um
1307 0 4B.21.2.3 I.ME5 : Minimum width of a ME5 slot region is 1.2um X 1.2um
1309 0 4B.21.2.3 I.ME4 : Minimum width of a ME4 slot region is 1.2um X 1.2um
1311 0 4B.21.2.3 I.ME3 : Minimum width of a ME3 slot region is 1.2um X 1.2um
1313 0 4B.21.2.3 I.ME2 : Minimum width of a ME2 slot region is 1.2um X 1.2um
1315 0 4B.21.2.3 I.ME1 : Minimum width of a ME1 slot region is 1.2um X 1.2um
1323 0 4B.21.2.3 J.ME6 : Exact space between two ME6 slot regions is 2.8um
1331 0 4B.21.2.3 J.ME5 : Exact space between two ME5 slot regions is 2.8um
1339 0 4B.21.2.3 J.ME4 : Exact space between two ME4 slot regions is 2.8um
1347 0 4B.21.2.3 J.ME3 : Exact space between two ME3 slot regions is 2.8um
1355 0 4B.21.2.3 J.ME2 : Exact space between two ME2 slot regions is 2.8um
1363 0 4B.21.2.3 J.ME1 : Exact space between two ME1 slot regions is 2.8um
1368 0 4B.21.2.3 K.a.ME6 : Minimum metal-8 enclosure of ME6 slot is 2.76um
1373 0 4B.21.2.3 K.a.ME5 : Minimum metal-8 enclosure of ME5 slot is 2.76um
1378 0 4B.21.2.3 K.a.ME4 : Minimum metal-8 enclosure of ME4 slot is 2.76um
1383 0 4B.21.2.3 K.a.ME3 : Minimum metal-8 enclosure of ME3 slot is 2.76um
1388 0 4B.21.2.3 K.a.ME2 : Minimum metal-8 enclosure of ME2 slot is 2.76um
1393 0 4B.21.2.3 K.a.ME1 : Minimum metal-8 enclosure of ME1 slot is 2.76um
1411 0 4B.21.2.3 K.ME6: Maximun metal-6 enclosure of metal-6 slot is 6.76um
1429 0 4B.21.2.3 K.ME5: Maximun metal-5 enclosure of metal-5 slot is 6.76um
1447 0 4B.21.2.3 K.ME4: Maximun metal-4 enclosure of metal-4 slot is 6.76um
1465 0 4B.21.2.3 K.ME3: Maximun metal-3 enclosure of metal-3 slot is 6.76um
1483 0 4B.21.2.3 K.ME2: Maximun metal-2 enclosure of metal-2 slot is 6.76um
1501 0 4B.21.2.3 K.ME1: Maximun metal-1 enclosure of metal-1 slot is 6.76um
1502 0 4B.21.2.3 L: Metal-6 slot over TMV_RDL is not allowed
1505 0 4B.21.2.3 N.a.VI1: Minimum space between two VI1 regions in pad area is 0.28um
1510 0 4B.21.2.3 O.a.VI1: Minimum VI1 to pad edge regions is 0.1um
1515 0 4B.21.2.3 PQ.VI1: Minimum via1 to metal-1 slot spacing is 0.2um, no via1 on metal-1 slot
1518 0 4B.21.2.3 N.a.VI2: Minimum space between two VI2 regions in pad area is 0.28um
1523 0 4B.21.2.3 O.a.VI2: Minimum VI2 to pad edge regions is 0.1um
1528 0 4B.21.2.3 PQ.VI2: Minimum via2 to metal-2 slot spacing is 0.2um, no via2 on metal-2 slot
1531 0 4B.21.2.3 N.a.VI3: Minimum space between two VI3 regions in pad area is 0.28um
1536 0 4B.21.2.3 O.a.VI3: Minimum VI3 to pad edge regions is 0.1um
1541 0 4B.21.2.3 PQ.VI3: Minimum via3 to metal-3 slot spacing is 0.2um, no via3 on metal-3 slot
1544 0 4B.21.2.3 N.a.VI4: Minimum space between two VI4 regions in pad area is 0.28um
1549 0 4B.21.2.3 O.a.VI4: Minimum VI4 to pad edge regions is 0.1um
1554 0 4B.21.2.3 PQ.VI4: Minimum via4 to metal-4 slot spacing is 0.2um, no via4 on metal-4 slot
1557 0 4B.21.2.3 N.a.VI5: Minimum space between two VI5 regions in pad area is 0.28um
1562 0 4B.21.2.3 O.a.VI5: Minimum VI5 to pad edge regions is 0.1um
1567 0 4B.21.2.3 PQ.VI5: Minimum via5 to metal-5 slot spacing is 0.2um, no via5 on metal-5 slot
1568 0 4B.21.2.3 Y.VI1: Minimum VI1 DENSITY under pad open is 12%
1569 0 4B.21.2.3 Y.VI2: Minimum VI2 DENSITY under pad open is 12%
1570 0 4B.21.2.3 Y.VI3: Minimum VI3 DENSITY under pad open is 12%
1571 0 4B.21.2.3 Y.VI4: Minimum VI4 DENSITY under pad open is 12%
1572 0 4B.21.2.3 Y.VI5: Minimum VI5 DENSITY under pad open is 12%
1574 0 Warning_VASS_PAD_M6SLOT: PAD Meatl Must insert Slot 
1576 0 Warning_VASS_PAD_M5SLOT: PAD Meatl Must insert Slot 
1578 0 Warning_VASS_PAD_M4SLOT: PAD Meatl Must insert Slot 
1580 0 Warning_VASS_PAD_M3SLOT: PAD Meatl Must insert Slot 
1582 0 Warning_VASS_PAD_M2SLOT: PAD Meatl Must insert Slot 
1615 0 4B.21.3.3C : Minimum ME6 ovelap TMV_RDL is 2.0um, no TMV_RDL outside ME6
1619 0 4B.21.3.3H : Meatl pad has the same size as AL_RDL pad
1621 0 4B.21.3.3I_20KA : Minimum width of a SLOT region is 2.4um X 2.4um
1629 0 4B.21.3.3J_20KA : Exact space between two metal-6 slot regions is 3um
1634 0 4B.21.3K.a.ME6 : Minimum metal-6 enclosure of metal-6 slot is 2.76um
1652 0 e4B21_3_3Kb_ME6: Maximun metal-6 enclosure of metal-6 slot is 6.76um
1654 0 4B.21.3.3L: SLOT inside of TMV_RDL and LMn must be remove
1681 0 Recommend_4B_21_3_4_ME1:RFPADMK under ME1 structure, must with upper Metal
1688 0 Recommend_4B_21_3_4_ME2:RFPADMK under ME2 structure, must with upper Metal
1693 0 Recommend_4B_21_3_4_ME3:RFPADMK under ME3 structure, must with upper Metal
1696 0 Recommend_4B_21_3_4_ME4:RFPADMK under ME4 structure, must with upper Metal
1698 0 Recommend_4B_21_3_4_ME5:RFPADMK under ME5 structure, must with upper Metal
1700 0 Recommend_4B_21_3_4I_M5 : Exact width of a SLOT region is 1.2um X 1.2um
1702 0 Recommend_4B_21_3_4I_M4 : Exact width of a SLOT region is 1.2um X 1.2um
1704 0 Recommend_4B_21_3_4I_M3 : Exact width of a SLOT region is 1.2um X 1.2um
1706 0 Recommend_4B_21_3_4I_M2 : Exact width of a SLOT region is 1.2um X 1.2um
1708 0 Recommend_4B_21_3_4I_M1 : Exact width of a SLOT region is 1.2um X 1.2um
1716 0 Recommend_4B_21_3_4J_M5_20KA : Exact space between two SLOT regions is 4.2um
1724 0 Recommend_4B_21_3_4J_M4_20KA : Exact space between two SLOT regions is 4.2um
1732 0 Recommend_4B_21_3_4J_M3_20KA : Exact space between two SLOT regions is 4.2um
1740 0 Recommend_4B_21_3_4J_M2_20KA : Exact space between two SLOT regions is 4.2um
1748 0 Recommend_4B_21_3_4J_M1_20KA : Exact space between two SLOT regions is 4.2um
1753 0 Recommend_4B_21_3_4Ka_ME5 : Minimum metal-5 enclosure of metal-5 slot is 2.76um
1771 0 Recommend_4B_21_3_4Kb_ME5: Maximun metal-5 enclosure of metal-5 slot is 6.76um
1776 0 Recommend_4B_21_3_4Ka_ME4 : Minimum metal-4 enclosure of metal-4 slot is 2.76um
1794 0 Recommend_4B_21_3_4Kb_ME4: Maximun metal-4 enclosure of metal-4 slot is 6.76um
1799 0 Recommend_4B_21_3_4Ka_ME3 : Minimum metal-3 enclosure of metal-3 slot is 2.76um
1817 0 Recommend_4B_21_3_4Kb_ME3: Maximun metal-3 enclosure of metal-3 slot is 6.76um
1822 0 Recommend_4B_21_3_4Ka_ME2 : Minimum metal-2 enclosure of metal-2 slot is 2.76um
1840 0 Recommend_4B_21_3_4Kb_ME2: Maximun metal-2 enclosure of metal-2 slot is 6.76um
1845 0 Recommend_4B_21_3_4Ka_ME1 : Minimum metal-1 enclosure of metal-1 slot is 2.76um
1863 0 Recommend_4B_21_3_4Kb_ME1: Maximun metal-1 enclosure of metal-1 slot is 6.76um
1866 0 Recommend_4B_21_3_4Na_VI1: Minimum space between two VI1 regions in pad area is 0.28um
1871 0 Recommend_4B_21_3_4Oa_VI1: Minimum VI1 to pad edge regions is 0.1um
1876 0 Recommend_4B_21_3_4PQ_VI1: Minimum via1 to metal-1 slot spacing is 0.2um, no via1 on metal-1 slot 
1879 0 Recommend_4B_21_3_4Na_VI2: Minimum space between two VI2 regions in pad area is 0.28um
1884 0 Recommend_4B_21_3_4Oa_VI2: Minimum VI2 to pad edge regions is 0.1um
1889 0 Recommend_4B_21_3_4PQ_VI2: Minimum via2 to metal-2 slot spacing is 0.2um, no via2 on metal-2 slot 
1892 0 Recommend_4B_21_3_4Na_VI3: Minimum space between two VI3 regions in pad area is 0.28um
1897 0 Recommend_4B_21_3_4Oa_VI3: Minimum VI3 to pad edge regions is 0.1um
1902 0 Recommend_4B_21_3_4PQ_VI3: Minimum via3 to metal-3 slot spacing is 0.2um, no via3 on metal-3 slot 
1905 0 Recommend_4B_21_3_4Na_VI4: Minimum space between two VI4 regions in pad area is 0.28um
1910 0 Recommend_4B_21_3_4Oa_VI4: Minimum VI4 to pad edge regions is 0.1um
1915 0 Recommend_4B_21_3_4PQ_VI4: Minimum via4 to metal-4 slot spacing is 0.2um, no via4 on metal-4 slot 
1918 0 Recommend_4B_21_3_4Na_VI5: Minimum space between two VI5 regions in pad area is 0.28um
1923 0 Recommend_4B_21_3_4Oa_VI5: Minimum VI5 to pad edge regions is 0.1um
1928 0 Recommend_4B_21_3_4PQ_VI5: Minimum via5 to metal-5 slot spacing is 0.2um, no via5 on metal-5 slot 
1929 0 Recommend_4B_21_3_4Y_VI1: Minimum VI1 DENSITY under pad open is 12%
1930 0 Recommend_4B_21_3_4Y_VI2: Minimum VI2 DENSITY under pad open is 12%
1931 0 Recommend_4B_21_3_4Y_VI3: Minimum VI3 DENSITY under pad open is 12%
1932 0 Recommend_4B_21_3_4Y_VI4: Minimum VI4 DENSITY under pad open is 12%
1933 0 Recommend_4B_21_3_4Y_VI5: Minimum VI5 DENSITY under pad open is 12%
1949 0 4B.22.2.2: Only ESD and I/O devices are permitted under BOAC pad
1951 0 4B.22.2C : Minimum width of a metal-6 slot region is 1.2um X 1.2um
1959 0 4B.22.2D : Exact space between two metal-6 slot regions is 2.8um
1964 0 4B.22.2Ea : Minimum metal-6 enclosure of metal-6 slot is 2.76um
1982 0 4B.22.2Eb: Maximun metal-6 enclosure of metal-6 slot is 6.76um
1984 0 4B.22.2F: SLOT inside of TMV_RDL and LMn must be remove
1990 0 4B.24A.a: Minimum width of MMC region is 3.9um
1999 0 4B.24A.b: Maximum MMC width is 100 um
2002 0 4B.24B: Minimum space between two MMC regions is 1.0um
2007 0 4B.24C: Minimum MMCBP ovelap MMC is 0.6um, no MMC outside MMCBP
2010 0 4B.24D: Minimum MMC ovelap TMV_RDL is 0.45um
2012 0 4B.24E: Minimum MMC to unrelated AL_RDL is 0.65um
2018 0 4B.24F: Minimum width of MMCBP region is 5.1um
2021 0 4B.24G: Minimum space between two MMCBP regions is 1.0um
2026 0 4B.24H:Minimum MMCBP ovelap TMV_RDL is 0.45um.
2028 0 4B.24I: Minimum MMC to unrelated Metal6 is 0.4um
2030 0 4B.24J: Minimum MMC to unrelated TMV_RDL is 1.0um
2032 0 4B.24K.a: Minimum and maximum width of TMV_RDL within MMCBP is 3.0um X 3.0um
2038 0 4B.24Kb: Minimum width of a TMV_RDL region is 4.0um X 4.0um
2044 0 4B.24Kc: Minimum width of a TMV_RDL within Fusemark region is 2.3um X 2.3um
2047 0 4B.24L.a: Minimum space between two TMV_RDL regions is 1.6um
2049 0 4B.24L.b: Minimum space between two TMV_RDL regions is 2.0um for TMV_RDL outside MMCBP
2057 0 4B.24M: Minimum width of AL_RDL region is 3.0um
2060 0 4B.24N.a: Minimum space between two AL_RDL regions is 0.9um
2068 0 4B.24O.a: Minimum AL_RDL ovelap TMV_RDL is 0.35um, no TMV_RDL outside AL_RDL
2071 0 4B.24O.b: Minimum AL_RDL ovelap TMV_RDL is 0.5um for TMV_RDL outside MIMBP
2076 0 4B.24P_20KA: Minimum last metal enclosure of TMV_RDL is 0.6um
2082 0 4B.24Q: Minimum Last dummy Metal block layer overlap MMCBP is 0.4um
2097 0 4B.25A:Maximum IND length and width is 320 um
2103 0 4B.25B:Minimum IND length and width is 30 um
2105 0 4B.25C_20KA:Minimum IND to IND spacing is 15.6um
2107 0 4B.25D:Minimum ME8 vertex within IND is 10 um
2108 0 4B.25E:IND shapes must be orthogonal rectangle
2117 0 4B.25G:Maximun ME8 width within IND is 10 um
2119 0 4B.25H_20KA:Minimun spacing IND METAL is 1.5 um
2120 0 4B.25I_20KA:Minimun spacing IND METAL to ME6 is 1.5 um
2128 0 4B.25K:Minimun NWEL to IND METAL is 10 um
2136 0 8.2A: Minimum width of AL_RDL region is 3.0um except fuse area
2142 0 8.2B: Minimum space between two AL_RDL regions (for not over the MIM CAP bottom) is 1.60um
2153 0 8.2C: Minimum space of Al-metal line to Al-metal line is 3um if either/both width > 35um
2159 0 8.2E: Minimum and maximum width of a TMV_RDL region outside fuse, pad and MIMCAP is 4.0um
2162 0 8.2F: Minimum space between two AL_RDL regions outside fuse, pad and MIMCAP is 2um
2167 0 8.2G_20KA: Minimum last copper metal overlap TMV_RDL is 0.6um, no floating RDL_TMV
2172 0 8.2H: Minimum AL_RDL enclosure of TMV_RDL outside fuse, pad and MIMCAP is 0.5um, no floating TMV_RDL
2180 0 8.3A__8.3D.b__8.3E.b: Maximum AL_RDL width without slotting is 20um when length is greater than 30um is 20um
2189 0 8.3B: Minimum and Maximum AL_RDL Slot width are 2um and 5um respectively
2204 0 8.3C: Minimum and Maximum AL_RDL Slot length are 10um and 250um respectively
2207 0 8.3D.a: Minimum space between AL_RDL slot regions is 9um
2212 0 8.3E.a: Minimum slot to Metal edge spacing 9 um
2237 0 SP_4A_1AB:Minimum dimension of an DIFF region is 0.042/0.06um
2238 0 SP_4B_1A:Minimum width of ME1 region is 0.08um
2245 0 SP_4B_1C:Minimum space between ME1 regions is 0.12um
2249 0 SP_4B_1D.a:Minimum ME1 overlap contac is -0.05um
2254 0 SP_OPC_DIFF:SP mark_layer must overlap diffusion OPC_BLOCK_LAYERS
2259 0 SP_OPC_POLY:SP mark_layer must overlap poly OPC_BLOCK_LAYERS
2264 0 SP_OPC_CONT:SP mark_layer must overlap contact OPC_BLOCK_LAYERS
2269 0 SP_OPC_M1:SP mark_layer must overlap metal-1 OPC_BLOCK_LAYERS
2271 0 SP_VTNH:SP mark_layer overlap VTNH layer is not allowed
2273 0 SP_VTPH:SP mark_layer overlap VTPH layer is not allowed
2282 0 SP_OPCT_BLOCK:SP OPC_BLOCK_LAYERS are only for SP SRAM 
2284 0 SP_OPCT_4A_15C:Minimum CONT area in CONTACT_OPC_BLOCK region is 0.0462 um2
2305 0 DP_4B_1A:Minimum width of ME1 region is 0.13um
2306 0 DP_4B_1C:Minimum space between ME1 regions is 0.15um
2310 0 DP_4B_1D.a:Minimum ME1 overlap CONT is -0.05um
2317 0 DP_HS_OPC_DIFF:DP(HS) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
2321 0 DP_HS_OPC_POLY:DP(HS) mark_layer must overlap poly OPC_BLOCK_LAYERS
2337 0 DP_HS_OPC_BLOCK:DP(HS) OPC_BLOCK_LAYERS are only for DP and 2PRFLL SRAM
2341 0 DP_LL_OPC_DIFF:DP(LL) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
2345 0 DP_LL_OPC_POLY:DP mark_layer must overlap poly OPC_BLOCK_LAYERS
2354 0 DP_LL_OPC_BLOCK:DP(LL) OPC_BLOCK_LAYERS are only for DP SRAM
2355 0 DP_LL_VTNH:DP(LL) must overlap VTNH
2356 0 DP_LL_VTPH:DP(LL) must overlap VTPH
2377 0 2PHD_4B_1A:Minimum width of ME1 region is 0.15um
2384 0 2PHD_4B_1C:Minimum space between ME1 regions is 0.16um
2385 0 2PHD_4B_1Da:Minimum ME1 overlap contac is 0um, no CONT outside ME1
2396 0 2PHD.HS_OPC_CELL_BLOCK:2PHD(HS) mark_layer must overlap C_CELL_Block
2397 0 2PHD_LL_OPC_VTNH:2PHD(LL) mark_layer must overlap VTNH
2398 0 e2PHD_LL_OPC_VTPH:2PHD(LL) mark_layer must overlap VTPH
2419 0 2PRF_4B_1A:Minimum width of ME1 region is 0.15um
2426 0 2PRF_4B_1C:Minimum space between ME1 regions is 0.16um
2427 0 2PRF_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
2428 0 2PRF_VTNH:2PRF mark_layer overlaps VTNH layer is not allowed
2429 0 2PRF_VTPH:2PRF mark_layer overlaps VTPH layer is not allowed
2430 0 2PRF_OPC_CELL_BLOCK:2PRF mark_layer must overlap C_CELL_Block
2451 0 2PRF_1_4B_1C:Minimum space between ME1 regions is 0.16um
2452 0 2PRF_1_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
2453 0 2PRF_1_VTNH:2PRF mark_layer overlaps VTNH layer is not allowed
2454 0 2PRF_1_VTPH:2PRF mark_layer overlaps VTPH layer is not allowed
2455 0 2PRF_1_OPC_CELL_BLOCK:2PRF mark_layer must overlap C_CELL_Block
2476 0 SPLL_4B_1A:Minimum width of ME1 region is 0.08um
2483 0 SPLL_4B_1C:Minimum space between ME1 regions is 0.12um
2487 0 SPLL_4B_1D.a:Minimum ME1 overlap CONT is -0.05um
2490 0 SPLL_OPC_DIFF:SPLL mark_layer must overlap diffusion OPC_BLOCK_LAYERS
2493 0 SPLL_OPC_POLY:SPLL mark_layer must overlap poly OPC_BLOCK_LAYERS
2496 0 SPLL_OPC_CONT:SPLL mark_layer must overlap contact OPC_BLOCK_LAYERS
2499 0 SPLL_OPC_M1:SPLL mark_layer must overlap metal-1 OPC_BLOCK_LAYERS
2508 0 SPLL.OPC_BLOCK:SPLL OPC_BLOCK_LAYERS are only for SPLL SRAM 
2509 0 SPLL_VTNH:SPLL mark_layer must overlap VTNH
2510 0 SPLL_VTPH:SPLL mark_layer must overlap VTPH
2512 0 SPLL.CONT_4A_15C:Minimum CONT area in CONTACT_OPC_BLOCK region is 0.0462 um2
2533 0 2PRFLL_4B_1A:Minimum width of ME1 region is 0.15um
2534 0 2PRFLL_4B_1C:Minimum space between ME1 regions is 0.16um
2535 0 2PRFLL_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
2536 0 2PRFLL_VTNH:2PRFLL mark_layer must overlap VTNH
2537 0 2PRFLL_VTPH:2PRFLL mark_layer must overlap VTPH
2558 0 DP2_4B_1A:Minimum width of ME1 region is 0.13um
2565 0 DP2_4B_1C:Minimum space between ME1 regions is 0.15um
2566 0 DP2_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
2572 0 DP2.HS_OPC_DIFF:DP2(HS) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
2575 0 DP2.HS_OPC_POLY:DP2(HS) mark_layer must overlap poly OPC_BLOCK_LAYERS
2584 0 DP2_HS_OPC_BLOCK:DP2(HS) OPC_BLOCK_LAYERS are only for DP2(HS) SRAM 
2587 0 DP2_LL_OPC.DIFF:DP2(LL) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
2591 0 DP2_LL_OPC.POLY:DP2(LL) mark_layer must overlap poly OPC_BLOCK_LAYERS
2600 0 DP2_LL_OPC_BLOCK:DP2(LL) OPC_BLOCK_LAYERS are only for DP2(LL) SRAM 
2601 0 DP2_LL_VTPH:DP2(LL) mark_layer must overlap VTPH
2602 0 DP2_LL_VTNH:DP2(LL) mark_layer must overlap VTNH
2605 0 OPC_BLOCK_DIFF:diffusion OPC block layer must be covered by SRAM mark layers(SP,SPLL,DP,DP2)
2608 0 OPC_BLOCK_POLY:poly OPC block layer must be covered by SRAM mark layers(SP,SPLL,DP,DP2) 
2611 0 OPC_BLOCK_CONT:contact OPC block layer must be covered by SRAM mark layers(SP,SPLL) 
2614 0 OPC_BLOCK_M1:metal1 OPC block layer must be covered by SRAM mark layers(SP,SPLL) 
2635 0 OPC_BLOCK_C_CELL_BLOCK.1:C_CELL_BLOCK layer must be covered by SRAM mark layers(2PRF_1,2PHD,2PRF,DP1)
2637 0 OPC_BLOCK_C_CELL_BLOCK.2:C_CELL_BLOCK layer overlaps VTNH or VTPH layers is not allowed
2659 0 SP_1_4B_1A:Minimum width of ME1 region is 0.08um
2660 0 SP_1_4B_1C:Minimum space between ME1 regions is 0.12um
2664 0 SP_1_4B_1D.a:Minimum ME1 overlap contac is -0.05um
2668 0 SP_1_OPC_DIFF:SP_1 mark_layer must overlap diffusion OPC_BLOCK_LAYERS
2672 0 SP_1_OPC_POLY:SP_1 mark_layer must overlap poly OPC_BLOCK_LAYERS
2674 0 SP_1_OPC_CONT:SP_1 mark_layer must overlap contact OPC_BLOCK_LAYERS
2678 0 SP_1_OPC_M1:SP_1 mark_layer must overlap metal-1 OPC_BLOCK_LAYERS
2679 0 SP_1_VTNH:SP_1 mark_layer overlap VTNH layer is not allowed
2680 0 SP_1_VTPH:SP_1 mark_layer overlap VTPH layer is not allowed
2693 0 SP_1.OPC_BLOCK:SP_1 OPC_BLOCK_LAYERS are only for SP_1 SRAM 
