0 0 dataAuditErrors
650 0 SkewEdge: 
668 0 4A.1AB: Minimum DIFFUSION width is 0.16um
678 0 4A.1C.a1_b1:Minimum DIFFUSION to DIFFUSION spacing is 0.20um
688 0 4A.1C.a2_b2: Minimum DIFFUSION to DIFFUSION spacing for 3.3V is 0.22um
701 0 4A.1D.a:Minimum N_WELL to N+ DIFFUSION (1.2V) spacing is 0.3um
702 0 4A.1D.b:Minimum N_WELL to N+ DIFFUSION (3.3V) spacing is 0.5um
710 0 4A.1E:Minimum N_WELL enclosure of N+ DIFFUSION is 0.16um
711 0 4A.1F:Minimum N_WELL to P+ DIFFUSION spacing is 0.16um
724 0 4A.1G.a:Minimum N_WELL enclosure of P+ DIFFUSION (1.2V) is 0.3um
729 0 4A.1G.b:Minimum N_WELL enclosure of P+ DIFFUSION (3.3V) is 0.5um
730 0 4A.1I:Minimum DIFFUSION/isolation area 0.1024 sq.um
738 0 4A.2A.a:Minimum width of an N-Well region is 0.63um
739 0 4A.2A.b:Minimum dimension of an N-Well resistor region is 1.5um
787 0 4A.2A.c:Maximum N-Well width for resistor is 20 um
789 0 4A.2B.a:Minimum N-Well to N-Well spacing is 0.63um
791 0 4A.2B.b1:Minium N-Well to non-potential(1.2V device) N-Well spacing is 1.0um
793 0 4A.2B.b2:Minimum N-Well to non-potential(3.3V device) N-Well spacing is 1.5um
794 0 4A.2B.c_d:Minimum spacing from N-well resistor to other N-Well regions is 2.2um
806 0 4A.2C/D: The resistor marker layer edges must either be entirely coincident with N-well edge or at least partially butted to N+ Tap (terminal).
813 0 4A.4A:Minimum T_WELL width is 0.63um
815 0 4A.4B.a:Minimum T_WELL to T_WELL spacing is 0.63um
817 0 4A.4B.b1:Minimum T_WELL to T_WELL spacing (1.2V) for non-equal-potential is 1.0um
819 0 4A.4B.b2: Minimum T_WELL to T_WELL spacing (3.3V) for non-equal-potential is 1.5um
824 0 4A.4C:Minimum N_WELL enclosure of T_WELL is 1.5um
831 0 4A.4D.a:Minimum T_WELL to P+ DIFFUSION (1.2V) spacing is 0.3um
832 0 4A.4D.b:Minimum T_WELL to P+ DIFFUSION (3.3V) spacing is 0.5um
838 0 4A.4E:Minimum T_WELL enclosure of P+ DIFFUSION is 0.16um
839 0 4A.4F:Minimum T_WELL to N+ DIFFUSION is 0.16um
857 0 4A.4G.a:Minimum T_WELL enclosure of N+ DIFFUSION (1.2V) is 0.3um
862 0 4A.4G.b:Minimum T_WELL enclosure of N+ DIFFUSION (3.3V) is 0.5um
867 0 4A.7A:Minimum width of VTN_SP region is 0.40um
872 0 4A.7B:Minimum space between two VTN_SP regions is 0.40um
884 0 4A.7C:Minimum VTN_SP extension over Poly gate is 0.16um
895 0 4A.7D:Minimum VTN_SP to unrelated Poly gate spacing is 0.28um
900 0 4A.8A: Minimum width of VTP_SP region is 0.40um
905 0 4A.8B: Minimum space between two VTP_SP regions is 0.40um
917 0 4A.8C: Minimum VTP_SP extension over Poly gate is 0.16um
928 0 4A.8D: Minimum VTP_SP to unrelated Poly gate spacing is 0.28um
933 0 4A.9A: Minimum width of VTNH region is 0.40um
938 0 4A.9B: Minimum space between two VTNH regions is 0.40um
950 0 4A.9C: Minimum VTNH extension over Poly gate is 0.16um
963 0 4A.9D: Minimum VTNH to unrelated Poly gate spacing is 0.28um
968 0 4A.10A: Minimum width of VTPH region is 0.40um
973 0 4A.10B: Minimum space between two VTPH regions is 0.40um
985 0 4A.10C: Minimum VTPH extension over Poly gate is 0.16um
998 0 4A.10D: Minimum VTPH to unrelated Poly gate spacing is 0.28um
1004 0 4A.11A:Minimum width of poly(1.2V low Vt NMOS) region is 0.12um
1005 0 4A.11B:Minimum width of VTNL region is 0.40um
1007 0 4A.11C:Minimum space between two VTNL regions is 0.40um
1010 0 4A.11D:Minimum VTNL overlap Diffusion is 0.3um
1011 0 4A.11E:Minimum VTNL to unrelated Diffusion spacing is 0.3um
1019 0 4A.11F:Minimum VTNL extension over poly on diffusion of related device is 0.4um
1026 0 4A.11G:Minimum VTNL to unrelated PO1 spacing is 0.4um
1031 0 4A.12A:Minimum width of poly(1.2V low Vt PMOS) region is 0.12um
1032 0 4A.12B:Minimum width of VTPL region is 0.40um
1034 0 4A.12C:Minimum space between two VTPL regions is 0.40um
1037 0 4A.12D:Minimum VTPL overlap Diffusion of related device is 0.3um
1038 0 4A.12E:Minimum VTPL to unrelated Diffusion spacing is 0.3um
1046 0 4A.12F:Minimum VTPL extension over poly on diffusion of related device is 0.4um
1056 0 4A.12G:Minimum VTPL to unrelated PO1 spacing is 0.4um
1064 0 4A.13A:Minimum width of poly(3.3V low Vt NMOS) region is 0.34um
1065 0 4A.13B:Minimum width of VTNHL region is 0.40um
1067 0 4A.13C:Minimum space between two VTNHL regions is 0.40um
1070 0 4A.13D:Minimum VTNHL overlap Diffusion is 0.3um
1071 0 4A.13E:Minimum VTNHL to unrelated Diffusion spacing is 0.3um
1078 0 4A.13F:Minimum VTNHL extension over poly on diffusion of related device is 0.4um
1088 0 4A.13G:Minimum VTPL to unrelated PO1 spacing is 0.4um
1097 0 4A.14A:Minimum width of poly(3.3V low Vt PMOS) region is 0.34um
1098 0 4A.14B:Minimum width of VTPHL region is 0.40um
1100 0 4A.14C:Minimum space between two VTPHL regions is 0.40um
1103 0 4A.14D:Minimum VTPHL overlap Diffusion of related device is 0.3um
1104 0 4A.14E:Minimum VTPHL to unrelated Diffusion spacing is 0.3um
1111 0 4A.14F:Minimum VTPHL extension over poly on diffusion of related device is 0.4um
1121 0 4A.14G:Minimum VTPHL to unrelated PO1 spacing is 0.4um
1124 0 4A.15A.a: Minimum width of poly(1.2V NMOS) region is 1.2um
1126 0 4A.15A.b: Minimum width of poly(3.3V NMOS) region is 1.8um
1132 0 4A.15B: Minimum NATIVE width is 1.60um
1134 0 4A.15C: Minimum NATIVE spacing is 0.63um
1146 0 4A.15D: Exact NATIVE enclosure of DIFFUSION is 0.3um
1147 0 4A.15E: Minimum NATIVE to unrelated Diffusion spacing is 0.25um
1151 0 4A.15F: Minimum NATIVE to N-WELL spacing is 0.9um
1152 0 4A.15J: NATIVE shapes must be orthogonal
1153 0 4A.15K: NATIVE must be within N+
1154 0 4A.Note.1: Two or more device in one Native region is not allowed
1160 0 4A.18A: Minimum width of TG region is 0.45um
1162 0 4A.18B: Minimum space between two TG regions is 0.45um
1164 0 4A.18C: Minimum TG overlap DIFF of 3.3V device is 0.3um
1165 0 4A.18D: Minimum TG to unrelated DIFF spacing is 0.3um
1170 0 4A.18E: Minimum TG extension over PO1 gate of 3.3V device is 0.4um
1173 0 4A.18F: Minimum TG to unrelated PO1 gate spacing is 0.4um
1189 0 4A.19AaBaC: Minimum poly1 width is 0.12um.
1191 0 4A.19Ab: Minimum poly1 width for 3.3V NMOS is 0.34um
1193 0 4A.19Bb: Minimum poly1 width for 3.3V PMOS is 0.30um
1204 0 4A.19D.a1_4A.19D.c1_4A.19D.c2.1: Minimum poly1 spacing is 0.2um.
1205 0 4A.19D.a2: Minimum poly1 spacing on DIFF regions without contact (as poly width >= 0.24um) is 0.24um.
1215 0 4A.19D.b1: Minimum poly1 spacing on DIFF regions with contacts is 0.26um
1216 0 4A.19D.b2: Minimum poly1 spacing on DIFF regions with contacts is 0.3um when PO1 width>0.24um.
1219 0 4A.19D.c2.2: Minimum space between two poly1 regions on field area is 0.24um when PO1 width>0.24um and common run length >1um
1231 0 4A.19E: Minimum overlap of a poly1 region extended into field oxide is 0.18um
1245 0 4A.19F: Minimum separation from an DIFF region to poly1 on field oxide is 0.10um
1257 0 4A.19G: Minimum poly1 endcap to RELATED DIFF spacing is 0.10um
1269 0 4A.19H.a__4A.19O: Minimum poly1 gate to field edge spacing is 0.20um
1288 0 4A.19H.b: Minimum poly1 gate (width > 0.24) to field edge spacing is 0.24 um
1294 0 4A.19I.a: Minimum poly1 gate width for 45 degree(1.2V) is 0.14um
1299 0 4A.19I.b: Minimum poly1 gate width for 45 degree(3.3V) is 0.38um
1313 0 4A.19J: 90 degree bent gate is not allowed.
1314 0 4A.19K: Maximum area of poly1 overlap of DIFF region is 80um x 80um.
1323 0 4A.19N:Minimum PO1 bent gate on field region to DIff spacing is 0.1um
1333 0 4A.19Q: POLY1 may only intersection DIFFUSION at 90 degrees , extra check POLY1 butting edge DIFFUSION
1346 0 4A.20A: Minimum HR width is 0.6um
1348 0 4A.20B: Minimum space between two HR regions is 0.6um
1349 0 4A.20C: Minimum HR poly1 width is 0.5um
1350 0 4A.20D: Minimum SAB width for HR PO1 resistor is 1.0um(define HR POLY length)
1355 0 4A.20E: Minimum HR enclosure of HR poly1 resistor
1356 0 4A.20F: Minimum HR to unrelated poly1 spacing is 2um
1360 0 4A.20G: Minimum HR poly to N+ spacing is 1.5um
1361 0 4A.20H: Minimum HR to PPLUS spacing is 0.5um
1366 0 4A.20I :Minimum SAB overlap HR poly1 resistor is 0.24um , extra check POLY1 inside HR region does not interact SAB
1367 0 4A.20J: Minimum HR poly1 contact to SAB spacing is 0.5um
1371 0 4A.20K: Minimum HR to diffusion spacing is 0.5um
1376 0 4A.20L: Minimum NWELL overlap HR poly1 resistor is 1.5um
1383 0 4A.20M: Min PPLUS overlap SAB is 0.2 um
1386 0 4A.20N: Minimum spacing from P+ implant to unrelated poly resistor is 0.4um
1675 0 4A.21M: Maximum NPLUS diffusion to nearest P+ pick-up spacing is 20um
1681 0 4A.22A: Minimum width of a PPLUS region is 0.24um
1686 0 4A.22B: Minimum space between two PPLUS regions is 0.24um
1692 0 4A.22C.a: Minimum PPLUS overlap P+ DIFF(inside N-Well) is 0.16um
1694 0 4A.22C.b: Minimum PPLUS overlap P+ DIFF(inside P-Well) is 0.06um
1703 0 4A.22D.a: Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.16um
1709 0 4A.22D.b: Minimum PPLUS to N+ DIFF spacing(inside N-Well) is 0.06um
1711 0 4A.22E: Minimum P+ diffusion to N+ diffusion is 0um
1712 0 4A.22F(4A.21G): Minimum PPLUS overlap DIFF to form P+ region is 0.16um
1714 0 4A.22G(4A.21F): Minimum DIFF extension over PPLUS to form N+ region is 0.16um
1715 0 4A.22H(4A.21I): Minimum PPLUS to PO1 spacing to form N+ S/D region is 0.24um
1720 0 4A.22I(4A.21H): Minimum PPLUS extension over PO1 to form P+ s/d is 0.24um
1722 0 4A.22J(4A.21K): Minimum PPLUS overlap CONT region is 0.10um, no butted contact.
1723 0 4A.22K(4A.21J): Minimum PPLUS to N+ CONT spacing is 0.10um
1733 0 4A.22L: Soft Contacts are prohibited
1990 0 4A.22M: Maximum P+ DIFF to nearest N+ pick-up spacing is 20um
1991 0 4A.22N: Minimun PPLUS area is 0.1764 sq.um
2012 0 4A.23A: Minimum SAB width is 0.40um
2014 0 4A.23B: Minimum SAB space is 0.40um
2015 0 4A.23C: Contact over SAB is not allowed.
2017 0 4A.23E: Minimum SAB extention over DIFF region is 0.2um
2034 0 4A.23Fa: Minimum SAB to PO1 spacing is 0.24um
2037 0 4A.23Fb: Minimum SAB to PO1 spacing is 0.2um
2038 0 4A.23G:Minimum SAB to unrelated DIFF spacing is 0.20um
2039 0 4A.23H.b: Minimum SAB to PO1 Contact spacing is 0.24um.
2041 0 4A.23J: Minimum SAB extension over DIFF resistor is 0.2um
2043 0 4A.23K: Minimum SAB extension over PO1 resistor is 0.2um
2047 0 4A.23L: Minimum SAB to contact spacing is 0.24um
2049 0 4A.23M: Minimum PPLUS overlap P+ poly1 resistor is 0.24um
2053 0 4A.23N: Minimum PPLUS to N+ (SAB) poly1 resistor spacing is 0.24um
2055 0 4A.23O: Minimum N-Well overlap P+ poly1 non-salicider resistor is 0.24um
2056 0 4A.23P: Minimum N-Well to N+ non-saliceder resistor spacing is 0.24um
2061 0 4A.23Q: Minimum N+ overlap N+ poly1 resistor is 0.24um
2065 0 4A.23R: Minimum N+ to P+ (SAB) poly1 resistor spacing is 0.24um
2066 0 4A.23S: Minimun SAB area is 0.37 sq.um
2075 0 4A.23T: Minimun SAB length for resistor is 1.0um
2078 0 4A.23U: Minimun poly1 width for non-salicide resistor is 0.5um
2081 0 4A.23V: Minimun diffusion width for non-salicide resistor is 0.5um
2082 0 4A.23Wa: Minimun TG to (SAB and PO1) of non-salicide resistor is 0.24um
2083 0 4A.23Wb: Minimun TG to (SAB and DIFF) of non-salicide resistor is 0.24um
2085 0 4A.23Xa: Minimun TG overlap (SAB and PO1) of non-salicide resistor is 0.24um
2087 0 4A.23Xb: Minimun TG overlap (SAB and DIFF) of non-salicide resistor is 0.24um
2098 0 4A.23Ya : N+ DIFFUSION non-salicide resistor should be drawn outside N_WELL
2099 0 4A.23Yb : P+ DIFFUSION non-salicide resistor should be drawn within N_WELL
2100 0 Recommend_4A.23Yc:TG over N+DIFFUSION and P+DIFFUSION non-salicide resistor are not recommended
2101 0 Recommend_4A.23Yd:TG over N+POLY1 and P+POLY1 non-salicide resistor are not recommended
2106 0 4A.23Za:Minimum N+POLY1 non-salicide resistor to P+ implant layer spacing is 0.24um
2107 0 4A.23Zb:Minimum N+ implant layer to  P+POLY1 non-salicide resistor spacing is 0.24um
2109 0 4A.23Zc:Minimum N_WELL layer extension to N+POLY1 non-salicide resistor is 0.24um
2120 0 4A.23Zd.a: Minimum N+ implant enclosure of (N+ POLY1 OVER SAB) is 0.20 um,  (POLY1 endcap is excepted from this rule)
2132 0 4A.23Zd.b: If SAB lies across POLY1,(POLY1 OVER SAB) partially covered,  by N+ and partially not covered by N+ is not allowed
2143 0 4A.23Ze.a: Minimum P+ implant enclosure of ((P+ POLY1 OVER SAB) NOT HR) is 0.20 um,  (POLY1 endcap is excepted from this rule)
2155 0 4A.23Ze.b: If SAB lies across POLY1,((POLY1 OVER SAB) NOT HR) partially covered,  by P+ and partially not covered by P+ is not allowed
2162 0 4A.23Zf.a: Minimum N+ implant enclosure of (N+ DIFFUSION OVER SAB) is 0.20 um,  (DIFFUSION endcap is excepted from this rule)
2169 0 4A.23Zf.b: (DIFFUSION OVER SAB) partially covered by N+ and partially not covered by N+ is not allowed
2176 0 4A.23Zg.a: Minimum P+ implant enclosure of (P+ DIFFUSION OVER SAB) is 0.20 um,  (DIFFUSION endcap is excepted from this rule)
2183 0 4A.23Zg.b: (DIFFUSION OVER SAB) partially covered by P+ and partially not covered by P+ is not allowed
2196 0 4A.24A: Exact CONT size is 0.16um
2206 0 4A.24B: Minimum space between two CONT regions is 0.20um
2217 0 4A.24C.a:Minimum DIFF CONT to poly1 gate spacing is 0.12um.
2218 0 4A.24C.b:Minimum DIFF CONT to poly1(3.3V) gate spacing is 0.14um.
2227 0 4A.24D:Minimum poly1 contact to diffusion spacing is 0.16um
2244 0 4A.24E: Minimum PO1 overlap CONT is 0.06um, no floating contact
2261 0 4A.24FG: Minimum extension of a diffusion region beyond a CONT region is 0.06um
2267 0 4A.24I: Poly contact on diffusion is not allowed.
2274 0 4A.25A: Minimum width of PESD region is 0.60um
2276 0 4A.25B: Minimum space between two PESD regions is 0.60um
2280 0 4A.26A: Minimum width of P_WELL_BLOCK region is 0.63um
2284 0 4A.26B: Minimum space between two P_WELL_BLOCK regions is 0.63um
2290 0 4A.26C: Minimum P_WELL_BLOCK to NATIVE spacing or notch is 0.63 um
2296 0 4A.26D: Minimum P_WELL_BLOCK to N_WELL spacing or notch is 0.90 um
2302 0 4A.26E: Minimum P_WELL_BLOCK to IND spacing or notch is 0.63 um
2305 0 4A.26F: Minimum P_WELL_BLOCK to DIFFUSION spacing is 0.25 um
2312 0 4A.26G: Minimum P_WELL_BLOCK enclosure of DIFFUSION is 0.30 um
2314 0 4A.26H: P_WELL_BLOCK overlap GATE is not allowed
2316 0 4A.26I: P_WELL_BLOCK overlap NWEL is not allowed
2318 0 4A.26J: P_WELL_BLOCK overlap IND is not allowed
2320 0 4A.26K: P_WELL_BLOCK overlap NATIVE is not allowed
2326 0 4A.26L: Minimum IND to NATIVE spacing is 0.63 um
2329 0 4A.26M: Minimum IND to N_WELL spacing is 0.90 um
2335 0 LOGO_5.1A_5.1C_suggested: Minimum width of DIFF region is 0.3um
2338 0 LOGO_5.1B: Minimum space between DIFF regions is 0.4um
2344 0 LOGO_5.2A_5.2C_suggested: Minimum width of NW region is 1.2um
2347 0 LOGO_5.2B: Minimum space between NW regions is 2um
2353 0 LOGO_5.3A_5.3C_suggested: Minimum width of TG region is 0.6um
2356 0 LOGO_5.3B: Minimum space between TG regions is 0.6um
2362 0 LOGO_5.4A_5.4C_suggested: Minimum width of PO1 region is 0.24um
2365 0 LOGO_5.4B: Minimum space between PO1 regions is 0.32um
2371 0 LOGO_5.5A_5.5C_suggested: Minimum width of NPLUS region is 0.42um
2374 0 LOGO_5.5B: Minimum space between NPLUS regions is 0.42um
2380 0 LOGO_5.6A_5.6C_suggested: Minimum width of PPLUS region is 0.42um
2383 0 LOGO_5.6B: Minimum space between PPLUS regions is 0.42um
2389 0 LOGO_5.7A_5.7C_suggested: Minimum width of SAB region is 0.6um
2392 0 LOGO_5.7B: Minimum space between SAB regions is 0.6um
2398 0 LOGO_5.8A_5.8C_suggested: Minimum width of CONT region is 0.32um
2401 0 LOGO_5.8B: Minimum space between CONT regions is 0.4um
2414 0 LOGO_5.8Da: Minimum PO1 enclosure of CONT is 0.14,
2432 0 LOGO_5.8Db: Minimum DIFFUSION enclosure of CONT is 0.14, floating CONT is not allowed
