*******************************************************************************
****** delay_chain schematic Project_Lib1  <vs>  delay_chain layout Project_Lib1
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(P_12_HSL130E, p_12_hsl130e) MOS                  4       4
(N_12_HSL130E, n_12_hsl130e) MOS                  4       4
                                             ------  ------
Total                                             8       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(N_12_HSL130E, n_12_hsl130e) MOS                  4       4           4       4
(P_12_HSL130E, p_12_hsl130e) MOS                  4       4           4       4
                                             ------  ------      ------  ------
Total                                             8       8           8       8

Schematic and Layout Match
