*******************************************************************************
****** inv schematic Project_Lib1  <vs>  inv layout Project_Lib1
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(P_12_HSL130E, p_12_hsl130e) MOS                  1       1
(N_12_HSL130E, n_12_hsl130e) MOS                  1       1
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(N_12_HSL130E, n_12_hsl130e) MOS                  1       1           1       1
(P_12_HSL130E, p_12_hsl130e) MOS                  1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

Schematic and Layout Match
