*******************************************************************************
****** delay_chain schematic Project_Lib1  <vs>  delay_chain layout Project_Lib1
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(inv schematic Project_Lib1, _) Cell             20       0*
(N_12_HSL130E, n_12_hsl130e) MOS                  0      20*
(P_12_HSL130E, p_12_hsl130e) MOS                  0      20*
                                             ------  ------
Total                                            20      40

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(N_12_HSL130E, n_12_hsl130e) MOS                 20      20          20      20
(P_12_HSL130E, p_12_hsl130e) MOS                 20      20          20      20
                                             ------  ------      ------  ------
Total                                            40      40          40      40

Schematic and Layout Match
