0 0 dataAuditErrors
1268 0 PWBLK_StampErrorFloat
1269 0 PWBLK_StampErrorMult
1270 0 PWBLK_StampErrorConnect
1276 0 PSUB_StampErrorFloat
1277 0 PSUB_StampErrorMult
1278 0 PSUB_StampErrorConnect
1283 0 wel_StampErrorFloat
1284 0 wel_StampErrorMult
1285 0 wel_StampErrorConnect
1290 0 TWEL_StampErrorFloat
1291 0 TWEL_StampErrorMult
1292 0 TWEL_StampErrorConnect
1298 0 PSUB_P_StampErrorFloat
1299 0 PSUB_P_StampErrorMult
1300 0 PSUB_P_StampErrorConnect
1305 0 B_DNW_StampErrorFloat
1306 0 B_DNW_StampErrorMult
1307 0 B_DNW_StampErrorConnect
1311 0  nsd/ptap butting issue: nsd/ptap need to be connected by metal and contact
1312 0  psd/ntap butting issue: psd/ntap need to be connected by metal and contact
1317 0 ptap is wrongly connected to POWER ! 
1323 0 ntap is wrongly connected to GROUND ! 
4588 0 malformed device NG_HS
4589 0 malformed device PG_HS
4590 0 malformed device MNGATE_C
4591 0 malformed device MPGATE_C
4592 0 malformed device NTGATE
4593 0 malformed device PTGATE
4594 0 malformed device NSGATE
4595 0 malformed device TGNSGATE
4596 0 malformed device NLGATE
4597 0 malformed device PLGATE
4598 0 malformed device NHLGATE
4599 0 malformed device PHLGATE
4600 0 malformed device NLGAT
4601 0 malformed device NHLGAT
4602 0 malformed device NLTWGATE
4603 0 malformed device NLTGTWGATE
4604 0 malformed device NG_LL
4605 0 malformed device PG_LL
4606 0 malformed device welres
4607 0 malformed device snyres_mm
4608 0 malformed device spyres_mm
4609 0 malformed device snpyr_mm
4610 0 malformed device sppyr_mm
4611 0 malformed device nshrpyr_wel
4612 0 malformed device nshrpyr_psub
4613 0 malformed device nsndres_mm
4614 0 malformed device nsppyr_wel
4615 0 malformed device nsppyr_psub
4616 0 malformed device dndiod_mm
4617 0 malformed device dpdiod_mm
4618 0 malformed device dnwdiod_mm
4619 0 malformed device CMMC
4620 0 malformed device bjt_v5_mm
4621 0 malformed device bjt_v10_mm
4622 0 malformed device bjt_v15_mm
4623 0 malformed device MNGATE_RF
4624 0 malformed device MPGATE_RF
4625 0 malformed device NTGATE_RF
4626 0 malformed device PTGATE_RF
4627 0 malformed device NSGATE_RF
4628 0 malformed device TGNSGATE_RF
4629 0 malformed device nshrpyr_rf
4630 0 malformed device nsppyr_rf
4631 0 malformed device nsnpyr_rf
4632 0 malformed device npn5x5_s_rf
4633 0 malformed device npn2_s_rf
4634 0 malformed device npn5x5_n_rf
4635 0 malformed device npn2_n_rf
4636 0 malformed device pnp5x5_n_rf
4637 0 malformed device pnp2_n_rf
4638 0 malformed device nsdtw_rf
4639 0 malformed device dpesd_rf
4640 0 malformed device varmis_rf12
4641 0 malformed device varmis_rf33
4642 0 malformed device vard_rf
4643 0 malformed device CMMC_RF
4645 0 malformed device MOMVP1_MM
4646 0 malformed device MOMVP1_RF
4648 0 malformed device MOMVP2_MM
4649 0 malformed device MOMVP2_RF
4650 0 malformed device MOM_MESH_SY_WEL
4651 0 malformed device MOM_MESH_SY_PSUB
4652 0 malformed device MOM_MESH_ASY_WEL
4653 0 malformed device MOM_MESH_ASY_PSUB
4654 0 malformed device p_rf_pad
4655 0 malformed device N_IND_CR_0
4656 0 malformed device N_IND_CR
4657 0 malformed device N_IND_CR_P
4658 0 malformed device N_IND_SY
4659 0 malformed device N_IND_SY_P
4660 0 malformed device N_IND_SYC
4661 0 malformed device N_IND_SYC_P
4662 0 malformed device N_IND_SQ_0
4663 0 malformed device N_IND_SQ
4664 0 malformed device N_IND_SQ_P
4665 0 malformed device MOM_ARRAY_VP3_RFVCL_1
4666 0 malformed device MOM_ARRAY_VP3_RFVCL_2
4667 0 malformed device MOM_ARRAY_VP3_RFVCL_3
4668 0 malformed device MOM_ARRAY_VP3_RFVCL_4
4669 0 malformed device MOM_ARRAY_VP4_RFVCL_1
4670 0 malformed device MOM_ARRAY_VP4_RFVCL_2
4671 0 malformed device MOM_ARRAY_VP4_RFVCL_3
4672 0 malformed device MOM_ARRAY_VP4_RFVCL_4
5303 0 unstable device for MOM_ARRAY_VP4_RFVCL_4_Device_85
5304 0 unpreserved device MOM_ARRAY_VP4_RFVCL_4_Device_85
5305 0 unstable device for MOM_ARRAY_VP4_RFVCL_3_Device_84
5306 0 unpreserved device MOM_ARRAY_VP4_RFVCL_3_Device_84
5307 0 unstable device for MOM_ARRAY_VP4_RFVCL_2_Device_83
5308 0 unpreserved device MOM_ARRAY_VP4_RFVCL_2_Device_83
5309 0 unstable device for MOM_ARRAY_VP4_RFVCL_1_Device_82
5310 0 unpreserved device MOM_ARRAY_VP4_RFVCL_1_Device_82
5311 0 unstable device for MOM_ARRAY_VP3_RFVCL_4_Device_81
5312 0 unpreserved device MOM_ARRAY_VP3_RFVCL_4_Device_81
5313 0 unstable device for MOM_ARRAY_VP3_RFVCL_3_Device_80
5314 0 unpreserved device MOM_ARRAY_VP3_RFVCL_3_Device_80
5315 0 unstable device for MOM_ARRAY_VP3_RFVCL_2_Device_79
5316 0 unpreserved device MOM_ARRAY_VP3_RFVCL_2_Device_79
5317 0 unstable device for MOM_ARRAY_VP3_RFVCL_1_Device_78
5318 0 unpreserved device MOM_ARRAY_VP3_RFVCL_1_Device_78
5319 0 unstable device for N_IND_SQ_P_Device_77
5320 0 unpreserved device N_IND_SQ_P_Device_77
5321 0 unstable device for N_IND_SQ_Device_76
5322 0 unpreserved device N_IND_SQ_Device_76
5323 0 unstable device for N_IND_SQ_0_Device_75
5324 0 unpreserved device N_IND_SQ_0_Device_75
5325 0 unstable device for N_IND_SYC_P_Device_74
5326 0 unpreserved device N_IND_SYC_P_Device_74
5327 0 unstable device for N_IND_SYC_Device_73
5328 0 unpreserved device N_IND_SYC_Device_73
5329 0 unstable device for N_IND_SY_P_Device_72
5330 0 unpreserved device N_IND_SY_P_Device_72
5331 0 unstable device for N_IND_SY_Device_71
5332 0 unpreserved device N_IND_SY_Device_71
5333 0 unstable device for N_IND_CR_P_Device_70
5334 0 unpreserved device N_IND_CR_P_Device_70
5335 0 unstable device for N_IND_CR_Device_69
5336 0 unpreserved device N_IND_CR_Device_69
5337 0 unstable device for N_IND_CR_0_Device_68
5338 0 unpreserved device N_IND_CR_0_Device_68
5339 0 unstable device for p_rf_pad_Device_67
5340 0 unpreserved device p_rf_pad_Device_67
5341 0 unstable device for MOM_MESH_ASY_PSUB_Device_66
5342 0 unpreserved device MOM_MESH_ASY_PSUB_Device_66
5343 0 unstable device for MOM_MESH_ASY_WEL_Device_65
5344 0 unpreserved device MOM_MESH_ASY_WEL_Device_65
5345 0 unstable device for MOM_MESH_SY_PSUB_Device_64
5346 0 unpreserved device MOM_MESH_SY_PSUB_Device_64
5347 0 unstable device for MOM_MESH_SY_WEL_Device_63
5348 0 unpreserved device MOM_MESH_SY_WEL_Device_63
5349 0 unstable device for MOMVP2_RF_Device_62
5350 0 unpreserved device MOMVP2_RF_Device_62
5351 0 unstable device for MOMVP2_MM_Device_60
5352 0 unpreserved device MOMVP2_MM_Device_60
5353 0 unstable device for MOMVP2_MM_Device_61
5354 0 unpreserved device MOMVP2_MM_Device_61
5355 0 unstable device for MOMVP1_RF_Device_59
5356 0 unpreserved device MOMVP1_RF_Device_59
5357 0 unstable device for MOMVP1_MM_Device_57
5358 0 unpreserved device MOMVP1_MM_Device_57
5359 0 unstable device for MOMVP1_MM_Device_58
5360 0 unpreserved device MOMVP1_MM_Device_58
5361 0 unstable device for CMMC_RF_Device_56
5362 0 unpreserved device CMMC_RF_Device_56
5363 0 unstable device for vard_rf_Device_55
5364 0 unpreserved device vard_rf_Device_55
5365 0 unstable device for varmis_rf33_Device_54
5366 0 unpreserved device varmis_rf33_Device_54
5367 0 unstable device for varmis_rf12_Device_53
5368 0 unpreserved device varmis_rf12_Device_53
5369 0 unstable device for dpesd_rf_Device_52
5370 0 unpreserved device dpesd_rf_Device_52
5371 0 unstable device for nsdtw_rf_Device_51
5372 0 unpreserved device nsdtw_rf_Device_51
5373 0 unstable device for pnp2_n_rf_Device_50
5374 0 unpreserved device pnp2_n_rf_Device_50
5375 0 unstable device for pnp5x5_n_rf_Device_49
5376 0 unpreserved device pnp5x5_n_rf_Device_49
5377 0 unstable device for npn2_n_rf_Device_48
5378 0 unpreserved device npn2_n_rf_Device_48
5379 0 unstable device for npn5x5_n_rf_Device_47
5380 0 unpreserved device npn5x5_n_rf_Device_47
5381 0 unstable device for npn2_s_rf_Device_46
5382 0 unpreserved device npn2_s_rf_Device_46
5383 0 unstable device for npn5x5_s_rf_Device_45
5384 0 unpreserved device npn5x5_s_rf_Device_45
5385 0 unstable device for nsnpyr_rf_Device_44
5386 0 unpreserved device nsnpyr_rf_Device_44
5387 0 unstable device for nsppyr_rf_Device_43
5388 0 unpreserved device nsppyr_rf_Device_43
5389 0 unstable device for nshrpyr_rf_Device_42
5390 0 unpreserved device nshrpyr_rf_Device_42
5391 0 unstable device for TGNSGATE_RF_Device_41
5392 0 unpreserved device TGNSGATE_RF_Device_41
5393 0 unstable device for NSGATE_RF_Device_40
5394 0 unpreserved device NSGATE_RF_Device_40
5395 0 unstable device for PTGATE_RF_Device_39
5396 0 unpreserved device PTGATE_RF_Device_39
5397 0 unstable device for NTGATE_RF_Device_38
5398 0 unpreserved device NTGATE_RF_Device_38
5399 0 unstable device for MPGATE_RF_Device_37
5400 0 unpreserved device MPGATE_RF_Device_37
5401 0 unstable device for MNGATE_RF_Device_36
5402 0 unpreserved device MNGATE_RF_Device_36
5403 0 unstable device for bjt_v15_mm_BJT_35
5404 0 unpreserved device bjt_v15_mm_BJT_35
5405 0 unstable device for bjt_v10_mm_BJT_34
5406 0 unpreserved device bjt_v10_mm_BJT_34
5407 0 unstable device for bjt_v5_mm_BJT_33
5408 0 unpreserved device bjt_v5_mm_BJT_33
5409 0 unstable device for CMMC_Device_32
5410 0 unpreserved device CMMC_Device_32
5411 0 unstable device for dnwdiod_mm_DIODE_31
5412 0 unpreserved device dnwdiod_mm_DIODE_31
5413 0 unstable device for dpdiod_mm_DIODE_30
5414 0 unpreserved device dpdiod_mm_DIODE_30
5415 0 unstable device for dndiod_mm_DIODE_29
5416 0 unpreserved device dndiod_mm_DIODE_29
5417 0 unstable device for nsppyr_psub_Device_28
5418 0 unpreserved device nsppyr_psub_Device_28
5419 0 unstable device for nsppyr_wel_Device_27
5420 0 unpreserved device nsppyr_wel_Device_27
5421 0 unstable device for nsndres_mm_Device_26
5422 0 unpreserved device nsndres_mm_Device_26
5423 0 unstable device for nshrpyr_psub_Device_25
5424 0 unpreserved device nshrpyr_psub_Device_25
5425 0 unstable device for nshrpyr_wel_Device_24
5426 0 unpreserved device nshrpyr_wel_Device_24
5427 0 unstable device for sppyr_mm_Device_23
5428 0 unpreserved device sppyr_mm_Device_23
5429 0 unstable device for snpyr_mm_Device_22
5430 0 unpreserved device snpyr_mm_Device_22
5431 0 unstable device for spyres_mm_Device_21
5432 0 unpreserved device spyres_mm_Device_21
5433 0 unstable device for snyres_mm_Device_20
5434 0 unpreserved device snyres_mm_Device_20
5435 0 unstable device for welres_RES_19
5436 0 unpreserved device welres_RES_19
5437 0 unstable device for PG_LL_MOS_18
5438 0 unpreserved device PG_LL_MOS_18
5439 0 unstable device for NG_LL_MOS_17
5440 0 unpreserved device NG_LL_MOS_17
5441 0 unstable device for NLTGTWGATE_MOS_16
5442 0 unpreserved device NLTGTWGATE_MOS_16
5443 0 unstable device for NLTWGATE_MOS_15
5444 0 unpreserved device NLTWGATE_MOS_15
5445 0 unstable device for NHLGAT_MOS_14
5446 0 unpreserved device NHLGAT_MOS_14
5447 0 unstable device for NLGAT_MOS_13
5448 0 unpreserved device NLGAT_MOS_13
5449 0 unstable device for PHLGATE_MOS_12
5450 0 unpreserved device PHLGATE_MOS_12
5451 0 unstable device for NHLGATE_MOS_11
5452 0 unpreserved device NHLGATE_MOS_11
5453 0 unstable device for PLGATE_MOS_10
5454 0 unpreserved device PLGATE_MOS_10
5455 0 unstable device for NLGATE_MOS_9
5456 0 unpreserved device NLGATE_MOS_9
5457 0 unstable device for TGNSGATE_MOS_8
5458 0 unpreserved device TGNSGATE_MOS_8
5459 0 unstable device for NSGATE_MOS_7
5460 0 unpreserved device NSGATE_MOS_7
5461 0 unstable device for PTGATE_MOS_6
5462 0 unpreserved device PTGATE_MOS_6
5463 0 unstable device for NTGATE_MOS_5
5464 0 unpreserved device NTGATE_MOS_5
5465 0 unstable device for MPGATE_C_MOS_4
5466 0 unpreserved device MPGATE_C_MOS_4
5467 0 unstable device for MNGATE_C_MOS_3
5468 0 unpreserved device MNGATE_C_MOS_3
5469 0 unstable device for PG_HS_MOS_2
5470 0 unpreserved device PG_HS_MOS_2
5471 0 unstable device for NG_HS_MOS_1
5472 0 unpreserved device NG_HS_MOS_1
